name: Build & Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          password: ${{ secrets.SSH_PASS }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/
            rm -rf todo-api
            git clone git@github.com:jpdrsanchez/todo-api.git
            cd todo-api
            npm install
            node ace build --production
            cd build
            npm ci --production
            pm2 start ecosystem.config.js
